<a href="https://colab.research.google.com/github/Saurabh77-99/MachineLearning/blob/main/Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Creating a Matrix using numpy

In [3]:
matrix_1 = np.array([[2,3],[6,7]])

In [4]:
print(matrix_1)

[[2 3]
 [6 7]]


In [5]:
matrix_1.shape

(2, 2)

In [6]:
matrix_2 = np.array([[10,35,45],[50,40,80],[20,15,90]])
print(matrix_2)

[[10 35 45]
 [50 40 80]
 [20 15 90]]


In [7]:
matrix_2.shape

(3, 3)

Creating matrices with random values

In [9]:
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[9.62774811e-01 8.09886352e-01 9.02005777e-01]
 [4.81335917e-04 3.16316899e-01 9.87471146e-01]
 [9.69201203e-01 5.43412188e-01 7.70233992e-01]]


In [11]:
random_matrix = np.random.randint(100,size=(4,5))
print(random_matrix)

[[ 5 61 56 24 45]
 [25 40  5 11  5]
 [28 33 77 33  6]
 [86 36 65 34 74]]


In [13]:
matrix_3 = np.ones((2,3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
matrix_3 = np.ones((2,3),dtype=int)
print(matrix_3)

[[1 1 1]
 [1 1 1]]


Null Matrix

In [17]:
matrix_null = np.zeros((2,3))
print(matrix_null)

[[0. 0. 0.]
 [0. 0. 0.]]


Identity Matrix

In [18]:
identity_matrix = np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Transpose of Matrix

In [19]:
a = np.random.randint(100,size=(2,3))
print(a)

[[77 87 72]
 [38 98 82]]


In [21]:
transpose_a = np.transpose(a)
print(transpose_a)

[[77 38]
 [87 98]
 [72 82]]
