<a href="https://colab.research.google.com/github/Saurabh77-99/MachineLearning/blob/main/Matrix2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Matrix addition

In [3]:
matrix_1 = np.array([[2,3],[4,5]])
matrix_2 = np.array([[10,35],[50,40]])
matrix_3 = matrix_1 + matrix_2
print(matrix_3)

[[12 38]
 [54 45]]


In [4]:
matrix_3.shape

(2, 2)

In [6]:
random_matrix1 = np.random.randint(10,size=(4,5))
random_matrix2 = np.random.randint(100,size=(4,5))
print(random_matrix1 + random_matrix2)

[[ 51  27  95  61  12]
 [ 61  47  36  52  55]
 [ 59  79  17  80 104]
 [ 66  36   0  13  64]]


In [8]:
sum = np.add(random_matrix1,random_matrix2)
print(sum)

[[ 51  27  95  61  12]
 [ 61  47  36  52  55]
 [ 59  79  17  80 104]
 [ 66  36   0  13  64]]


In [9]:
diff = np.subtract(random_matrix1,random_matrix2)
print(diff)

[[-49 -23 -87 -57 -10]
 [-61 -33 -20 -48 -53]
 [-43 -61 -17 -62 -88]
 [-52 -24   0 -13 -46]]


In [19]:
x = 5
y = np.random.randint(10,size=(4,4))
print(y)

[[3 9 9 8]
 [1 7 6 0]
 [1 1 1 4]
 [5 5 3 8]]


In [20]:
product = np.dot(x,y)

In [21]:
print(product)

[[15 45 45 40]
 [ 5 35 30  0]
 [ 5  5  5 20]
 [25 25 15 40]]


In [22]:
y = np.random.randint(10,size=(4,4))
x = np.random.randint(10,size=(4,4))
product = np.dot(x,y)
print(product)

[[ 97  63 129 102]
 [111  90 153 140]
 [ 65  38  72  79]
 [ 16   2  20  18]]


Element wise multiplication

In [18]:
y = np.random.randint(10,size=(4,4))
x = np.random.randint(10,size=(4,4))
product = np.multiply(x,y)
print(product)

[[ 0 63 81  0]
 [40 40 20  2]
 [ 0 16 32  8]
 [ 0  3 12  0]]
