<a href="https://colab.research.google.com/github/Saurabh77-99/MachineLearning/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

List vs Numpy -  Time Taken


In [ ]:
from time import process_time

Time Taken By a List

In [ ]:
py_list = [i for i in range(1000000)]

start_time = process_time()

py_list = [i+5 for i in py_list]

end_time = process_time()

print(end_time - start_time)

0.08825223400000004


In [ ]:
np_array = np.array([i for i in range(1000000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.0011323119999997466


Numpy Arrays

In [ ]:
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
nparr = np.array([1,2,3,4,5])
print(nparr)
type(nparr)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
#creating a 1D array
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
a.shape

(5,)

In [ ]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)
b.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [ ]:
c = np.array([(1,2,3,4),(1,2,3,4)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]]


Initial Placeholder in Numpy Arrays

In [ ]:
# create a numpy arrays of Zeroes
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# create a numpy arrays of Ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# array of particular values
z = np.full((3,3),5)
print(z)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [ ]:
# create an identity matrix
d = np.eye(4)
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# create numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.4171676  0.08371459 0.22258022 0.73698001]
 [0.20503978 0.96365979 0.70176691 0.4835256 ]
 [0.91289837 0.4791212  0.03144812 0.54141516]]


In [ ]:
# create numpy array with random values but integer and range
b = np.random.randint(10,100,(3,3))
print(b)

[[54 25 27]
 [22 50 51]
 [59 46 85]]


In [ ]:
# array of evenly spaced value -- specifying the number of values required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [ ]:
# array of evenly spaced value -- specifying the STEP
d = np.arange(10,30,5)
print(d)

[10 15 20 25]


In [ ]:
# convert list to numpy array
list2 = [10,20,30,40,50]
np_arr = np.asarray(list2);
print(np_arr)
type(np_arr)

[10 20 30 40 50]


numpy.ndarray

Analysing a Numpy Array

In [ ]:
c = np.random.randint(10,90,(5,5))
print(c)

[[71 54 43 69 43]
 [46 11 14 30 54]
 [27 80 47 66 28]
 [42 64 86 71 65]
 [27 28 80 41 73]]


In [ ]:
# array dimension
print(c.shape)

(5, 5)


In [ ]:
# number of dimensions
print(c.ndim)

2


In [ ]:
# number of elements in array
print(c.size)

25


In [ ]:
# checking datatype of values in the array
print(c.dtype)

int64


Mathematical operations on  numpy array

In [ ]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2) #concat the two string

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a = np.random.randint(1,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[7 4 6]
 [9 1 4]
 [6 2 7]]
[[14 16 12]
 [17 16 12]
 [10 17 19]]


In [ ]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[21 20 18]
 [26 17 16]
 [16 19 26]]
[[ -7 -12  -6]
 [ -8 -15  -8]
 [ -4 -15 -12]]
[[ 98  64  72]
 [153  16  48]
 [ 60  34 133]]
[[0.5        0.25       0.5       ]
 [0.52941176 0.0625     0.33333333]
 [0.6        0.11764706 0.36842105]]


In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[21 20 18]
 [26 17 16]
 [16 19 26]]
[[ -7 -12  -6]
 [ -8 -15  -8]
 [ -4 -15 -12]]
[[ 98  64  72]
 [153  16  48]
 [ 60  34 133]]
[[0.5        0.25       0.5       ]
 [0.52941176 0.0625     0.33333333]
 [0.6        0.11764706 0.36842105]]


Array Manipulation

In [ ]:
array = np.random.randint(1,10,(2,3))
print(array)
print(array.shape)

[[9 5 8]
 [8 6 1]]
(2, 3)


In [ ]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[9 8]
 [5 6]
 [8 1]]
(3, 2)


In [ ]:
trans2 = array.T
print(trans2)
print(trans.shape)

[[9 8]
 [5 6]
 [8 1]]
(3, 2)


In [ ]:
# reshaping of array
a = np.random.randint(1,10,(4,3))
print(a)
print(a.shape)

[[7 4 1]
 [9 5 7]
 [3 8 8]
 [3 9 2]]
(4, 3)


In [ ]:
b = a.reshape(3,4)
print(b)
print(b.shape)

[[7 4 1 9]
 [5 7 3 8]
 [8 3 9 2]]
(3, 4)
